### ISSUE TITLE
setterm command failing: "xterm does not support --blank" and "Inappropriato ioctl for device"

### ISSUE THREAD

**Issue by bjoli** [mdrjr/cloudshell_lcd#2]
Hi there!

The "setterm" command fails to set any powersave mode for the small tft screen. 

Runing 
    setterm -blank 0 -powersave off  > /dev/tty1

gives me 
    setterm: terminal xterm does not support --blank
    setterm: cannot (un)set powersave mode: Inappropriate ioctl for device

on the latest ubuntu image available on the wiki with an updated kernel. 

I also have the same problem with arch linux arm.

I have tried to figure out the problem, but the only thing I have noticed is that /dev/tty1 has it's $TERM set to "xterm" instead of the usual "linux".

**Comment by bjoli** [comment]
I fixed it by adding consoleblank=0 (or whatever it was) to the boot parameters.

**Comment by greenorca** [comment]
Hi there,

I added consoleblank=0 to the boot options in /media/boot/boot.ini and now the display stays on permanently. Running Odroid  on ubuntu1604 headless,  I'd love to be able to wake the display using a GPIO-button.  Any suggestions?

Thanks a lot
Sven

**Comment by greenorca** [comment]
If setterm via ssh fails, the following command helps to wake the display via ssh:

`echo -ne "\033[9;2]" > /dev/tty1`

The second parameter (2) is the time in minutes, when the display goes back to sleep again.

**Comment by thanhlev** [comment]
what does the command do?
echo -ne "\033[9;2]" > /dev/tty1

**Comment by mdrjr** [comment]
This script was never meant to be run on a xterm.
But since you are running it and probably enjoying it..
Its just to setup the blank (sort of screensaver).

I believe you can ignore it

2017-08-11 21:44 GMT-07:00 quangthanh010290 <notifications@github.com>:

**Comment by synkoptik** [comment]
bjoli, how do I set the consoleblank=0 to the boot parameters?

**Comment by slave5tom** [comment]
This work for me.  I updated the boot parameters by following the guide on https://wiki.ubuntu.com/Kernel/KernelBootParameters
Permanently Add a Kernel Boot Parameter
1) Log in to the system and start a terminal window.
2) Edit the /etc/default/grub file >>sudo nano /etc/default/grub
'## If the file /etc/default/grub appears to be empty or does not exist, see the instructions for earlier releases above in https://wiki.ubuntu.com/Kernel/KernelBootParameters. 
3) In the editor window, use the arrow keys to move the cursor to the line beginning with "GRUB_CMDLINE_LINUX_DEFAULT" then edit that line, adding your parameter(s) to the text inside the double-quotes after the existing text (to disable Power Saving Mode add consoleblank=0 inside the quotes) 
 GRUB_CMDLINE_LINUX_DEFAULT="nomdmonddf nomdmonisw **consoleblank=0**"
 its a good practice to add a comment line to explain what you did.  Use the '#' character at the start of the line to indicate it is a comment.
'# added consoleblank=0 20180224 to stop power saving mode'
4) overwrite the nano file ctrl+o and exit nano ctrl+x
5) update grup >>sudo update-grub
6) Restart the system. 
Note: The parameter(s) you've added to the GRUB_CMDLINE_LINUX_DEFAULT line are persistent, and will be in effect for every subsequent boot session (unless you remove them by repeating the procedure above).

**Comment by RaymondDay61** [comment]
> what does the command do?
> echo -ne "\033[9;2]" > /dev/tty1

This does work on a server. But after about a day or so the screen will come back on without touching the keyboard. So I made a /var/spool/cron/crontabs/root file to do this command every day at midnight. So the file named root looks like this:

```
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/tmp/crontab.TMeldP/crontab installed on Mon Dec  7 16:44:19 2020)
# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
@daily echo -ne "\033[9;2]" > /dev/tty1 #Set screen to turn off after no use.
```
I don't think this is the right way to do it but it works.

-Raymond Day
