### ISSUE TITLE
Arch Linux

### ISSUE THREAD

**Issue by skilbjo** [mdrjr/cloudshell_lcd#4]
Hi, what would it take to turn this project into an arch linux package, placed on the AUR (https://aur.archlinux.org/) ?

**Comment by mdrjr** [comment]
I have no idea.. You have a better change asking people who actually understand/knows Arch to check it

**Comment by skilbjo** [comment]
I'll fork it and figure it out. Maybe if/when I get it working you can merge it back to master, with instructions on a debian install, and instructions on an arch linux install.

**Comment by skilbjo** [comment]
Forked project over here: https://github.com/skilbjo/cloudshell-archlinux

I don't know how to create a arch linux package yet, so the way to install this for future users is:

`$ git clone https://github.com/skilbjo/cloudshell-archlinux; cd cloudshell-archlinux`
`$ sudo pacman -S bc curl sysstats`
`$ sudo ./src/run`
