### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by razvanrudy** [mdrjr/cloudshell_lcd#8]
Hi , the file is no longer avilable or link broken?

**Comment by mdrjr** [comment]
What file?

Em sáb, 12 de jan de 2019 15:23, razvanrudy <notifications@github.com
escreveu:

**Comment by mdrjr** [comment]
what file?

**Comment by IanMHoffman** [comment]
I believe he clicked the wget link in the readme which results in a 404.

**Comment by razvanrudy** [comment]
Not using this anymore.
